#!/usr/bin/env python3
import argparse
import importlib.util
from pathlib import Path


def load_sister_coverage_script(sister_repo):
    script = sister_repo / "scripts" / "check_efont_coverage.py"
    spec = importlib.util.spec_from_file_location("jpdict_coverage", script)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def is_japanese_cjk(ch):
    cp = ord(ch)
    return (
        0x3040 <= cp <= 0x30FF
        or 0x3400 <= cp <= 0x4DBF
        or 0x4E00 <= cp <= 0x9FFF
        or 0xF900 <= cp <= 0xFAFF
        or 0x20000 <= cp <= 0x3134F
        or cp in (0x3005, 0x3006, 0x3007, 0x301C)
    )


def read_codepoint_file(path):
    codepoints = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            codepoints.add(int(line, 16))
    return codepoints


def main():
    parser = argparse.ArgumentParser(description="Generate CJK UI codepoints used by the Japanese dictionary payload.")
    parser.add_argument("--sister-repo", default="../cardputer-jpdict", help="Path to cardputer-jpdict")
    parser.add_argument("--jpdict", default="build/sd/jpdict", help="jpdict payload path inside sister repo")
    parser.add_argument("--kanji", default="build/sd/kanji", help="kanji payload path inside sister repo")
    parser.add_argument("--base-codepoints", default="scripts/codepoints_jis_level1_2.txt")
    parser.add_argument("--output", default="scripts/codepoints_japanese_dictionary.txt")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    sister_repo = (project_root / args.sister_repo).resolve()
    coverage = load_sister_coverage_script(sister_repo)

    base_codepoints = read_codepoint_file(project_root / args.base_codepoints)
    wanted = set(base_codepoints)
    sources = {
        "jpdict.term": 0,
        "kanji.candidates": 0,
    }
    skipped_non_bmp = set()

    scanners = [
        coverage.scan_jpdict(str(sister_repo / args.jpdict)),
        coverage.scan_kanji(str(sister_repo / args.kanji)),
    ]
    for scanner in scanners:
        for source, text in scanner:
            if source not in sources:
                continue
            for ch in text:
                if not is_japanese_cjk(ch):
                    continue
                cp = ord(ch)
                if cp > 0xFFFF:
                    skipped_non_bmp.add(cp)
                    continue
                if cp not in base_codepoints:
                    sources[source] += 1
                wanted.add(cp)

    output = project_root / args.output
    with open(output, "w", encoding="utf-8") as f:
        f.write("# JIS X 0208 Level 1/2 plus BMP Japanese dictionary headword and kanji candidate glyphs.\n")
        f.write("# Generated by scripts/generate_japanese_dictionary_codepoints.py\n")
        for cp in sorted(wanted):
            f.write(f"{cp:04X}\n")

    print(f"wrote {len(wanted)} BMP codepoints to {output}")
    print(f"base={len(base_codepoints)} added={len(wanted - base_codepoints)}")
    print(f"non_bmp_skipped={len(skipped_non_bmp)}")
    for source, count in sources.items():
        print(f"{source}_non_base_occurrences={count}")


if __name__ == "__main__":
    main()
